name: auryo
version: {VERSION}
summary: A SoundCloud client for your desktop
description: |
  Listen to SoundCloud® from the comfort of your desktop. Use keyboard
  shortcuts to navigate through your music. Be more productive.
grade: stable
confinement: strict

parts:
  auryo:
    plugin: dump
    source: https://github.com/Superjo149/auryo/releases/download/v{VERSION}/Auryo_{VERSION}_amd64.deb
    source-type: deb
    after:
      - desktop-gtk3
    # Correct path to icon.
    # Clear the execstack - https://forum.snapcraft.io/t/snap-and-executable-stacks/1812
    prepare: |
      sed -i 's|Icon=auryo|Icon=/usr/share/icons/hicolor/256x256/apps/auryo\.png|' usr/share/applications/auryo.desktop
      execstack --clear-execstack opt/Auryo/auryo
    build-packages:
      - execstack
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6

apps:
  auryo:
    command: bin/desktop-launch $SNAP/opt/Auryo/auryo --no-sandbox
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    plugs:
      - bluez
      - browser-support
      - gsettings
      - home
      - mount-observe
      - network
      - opengl
      - pulseaudio
      - unity7
      - x11

slots:
  auryo-player-mpris:
    interface: mpris
    name: auryo_player